"""add phone number

Revision ID: 5204b4b142ec
Revises: a91fb5dcbc93
Create Date: 2023-12-03 15:19:52.971208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5204b4b142ec"
down_revision: Union[str, None] = "a91fb5dcbc93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number"))
    # ### end Alembic commands ###
